### ISSUE TITLE
Installation error and backup error

### ISSUE THREAD

**Issue by PlebRick** [remcoros/webtop-sparrow-startos#4]
Installed the service. It does run. However, upon installation it gives errors and also gives errors when backing up

Install error:
Install of webtop-sparrow@1.8.2.1 Failed: Filesystem I/O Error: error reading a body from connection: end of file before message length reached

Backup error:
Failed: Backup Error: error: Found argument '/config' which wasn't expected, or isn't valid in this context USAGE: compat duplicity create <mountpoint> <datapath> For more information try --help

**Comment by remcoros** [comment]
I'll leave this open until we know for sure the installation error is a connection error or an issue with the package (I suspect the former)

**Comment by remcoros** [comment]
The latest pre-release reduced the package size by a lot. This might help a bit when uploading the .s9pk trough a browser.

I'll close this for now. If you still have or find issues, feel free to open a new ticket!
